var canvs;
var score;
var button;
function setup() {
    canvas = createCanvas(100, 100);
    createP('click the canvas to get points');
    score = 0;
    button = createButton("click");
    button.mousePressed(increaseScore);

    var firebaseConfig = {
        apiKey: "AIzaSyD1_jxN2FHoFLZL7FY9it-8kPuhN0VIT_s",
        authDomain: "thanks-dan.firebaseapp.com",
        databaseURL: "https://thanks-dan.firebaseio.com",
        projectId: "thanks-dan",
        storageBucket: "thanks-dan.appspot.com",
        messagingSenderId: "979588923471",
        appId: "1:979588923471:web:fe93a2bcc34c545bd32a3a",
        measurementId: "G-DQSP0GDDRL"
      };
      firebase.initializeApp(firebaseConfig);
      console.log(firebase);

      var database = firebase.database;
      //how is data orginized in firebase
      //orginized in a tree like structere just like a jso 
      //the way to acces the tree like strucure is with a ref
      //scores:   is an array of id,(generated by firebase), and
        //each id has a score and a name
    //so how do you access the ref as a path
    var ref = database.ref('scores');

    //now put data in there

    var data = {
        name: "dts",
        score: 43
    }


}

function draw() {
    background(0,40,500);
    textAlign(CENTER);
    textSize(32);
    text(score,width / 2, height / 2);

}

function increaseScore(){
    score++;
}

